 Document.apply()

Document.apply()
Document.apply(function{})
Document.apply()
Document.apply()
Document.apply()
Document.apply()
Document.apply()
Document.apply()
Document.apply()
Document.apply()
Document.apply()
Document.apply()
Document.apply()
